CREATE TABLE IF NOT EXISTS aluno (
  aluno_id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  cpf CHAR(14) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  plano VARCHAR(60) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
