CREATE TABLE IF NOT EXISTS pagamento (
  pagamento_id BIGSERIAL PRIMARY KEY,
  aluno_nome VARCHAR(150) NOT NULL,
  valor NUMERIC(10, 2) NOT NULL,
  status VARCHAR(30) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avaliacao_evolucao (
  avaliacao_id BIGSERIAL PRIMARY KEY,
  aluno_nome VARCHAR(150) NOT NULL,
  teste VARCHAR(120) NOT NULL,
  evolucao VARCHAR(80) NOT NULL,
  status VARCHAR(30) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS professor (
  professor_id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  especialidade VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL,
  comissao NUMERIC(10, 2) NOT NULL DEFAULT 0,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS equipamento (
  equipamento_id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  unidade VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL,
  proxima_manutencao VARCHAR(30),
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS insumo_produto (
  insumo_id BIGSERIAL PRIMARY KEY,
  produto VARCHAR(150) NOT NULL,
  categoria VARCHAR(120) NOT NULL,
  estoque INTEGER NOT NULL,
  status VARCHAR(30) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notificacao (
  notificacao_id BIGSERIAL PRIMARY KEY,
  canal VARCHAR(30) NOT NULL,
  segmento VARCHAR(120) NOT NULL,
  mensagem TEXT NOT NULL,
  status VARCHAR(30) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS preferencia_notificacao (
  usuario_id BIGINT PRIMARY KEY,
  email_habilitado BOOLEAN NOT NULL DEFAULT TRUE,
  sms_habilitado BOOLEAN NOT NULL DEFAULT TRUE,
  push_habilitado BOOLEAN NOT NULL DEFAULT TRUE,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
