ALTER TABLE aluno
ADD COLUMN IF NOT EXISTS telefone VARCHAR(30),
ADD COLUMN IF NOT EXISTS data_nascimento VARCHAR(20),
ADD COLUMN IF NOT EXISTS endereco VARCHAR(255),
ADD COLUMN IF NOT EXISTS objetivo VARCHAR(255),
ADD COLUMN IF NOT EXISTS contato_emergencia VARCHAR(255);